export const GET_PRODUCT = 'GETPRODUCT'
export const GET_USERS = 'GETUSERS'
export const ADD_CART = 'ADDCART'

export const DECREMENT_COUNT_PAY = 'DECREMENTCOUNTPAY'
export const DECREMENT_COUNT_PAY_PROFILE = 'DECREMENTCOUNTPAYPROFILE'
export const DECREMENT_COUNT_PAY_BY_CART = 'DECREMENTCOUNTPAYBYCART'
export const INCREMENT_COUNT_PAY_BY_CART = 'INCREMENTCOUNTPAYBYCART'

// ------- cart

export const INCREMENT_PROJECT = 'INCREMENTPROJECT'
export const DECREMENT_PROJECT = 'DECREMENTPROJECT'
export const DELETE_ITEM_CART = 'DELETEITEMCART'
export const DELETE_LIST_ITEM_CART = 'DELETELISTITEMCART'
export const NUMBER_INPUT = 'NUMBERINPUT'
export const PAY_CART = 'PAYCART'
export const KEYWORD_SEARCH = 'KEYWORDSORT'
export const ADD_CART_BY_PROFILE = 'ADDCARTBYPROFILE'

export const ONCHANGE_NUMBER_INPUT_BY_CART = 'ONCHANGENUMBERINPUTBYCART'
export const SET_EVALUATE = 'SETEVALUATE'

export const DELETE_ITEM_BY_PAY_CART = 'DELETEITEMBYPAYCART'
export const PAY_CART_NO_USER = 'PAYCARTNOUSER'
